backend:
  name: git-gateway
  repo: "Justin-way/justway" # blog 存放在 Github repo 的位置
  branch: "master" # 分支
  site_url: "https://github.com/Justin-way/justway" # 你的網站網址

media_folder: "static/img" # 存放多媒體的資料夾
public_folder: "/img"
locale: "zh_Hant" # 語系 https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-locales/src

collections:
  - name: "blogs"
    label: "博客"
    folder: "content/blogs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發布日期", name: "date", widget: "datetime" }
      - { label: "草稿", name: "draft", widget: "boolean" }
      - { label: "描述", name: "description", widget: "string" }
      - { label: "類型", name: "type", widget: "string" }
      - { label: "內容", name: "body", widget: "markdown" }
